### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by Kulitorum** [dillonhuff/gpr#1]
Nice code, but please make it a habbit to add comments.

What is a chunk?
What is a block?

How can I see the data in the debugger? (QT Creator)

Thanks :)

**Comment by dillonhuff** [comment]
Thanks for your comment Kulitorum!

I have added comments above class chunk and class block in an attempt to clarify what they are. Please let me know if you find them helpful as an explanation.

I'm not sure what you mean by "How can I see the data in the debugger? (QT Creator)" I have never used QT Creator. Could you clarify?

**Comment by Kulitorum** [comment]
Thanks. makes more sense now :)

FYI, here's the changes I have to make to compile on MSVC 15: (> lines are the fixes)

gcode_program.h:191: error: C2039: 'unique_ptr': is not a member of 'std'
>#include <memory>

gcode_program.h:18: error: C4716: 'gpr::address::addr_tp': must return a value
>virtual address_type addr_tp() const { assert(false); return ADDRESS_TYPE_INTEGER;}

gcode_program.h:104: error: C4716: 'gpr::chunk::tp': must return a value
>virtual chunk_type tp() const { assert(false); return CHUNK_TYPE_COMMENT;}
---------------------------------------------
In terms seeing data in the debugger, this is what I can see when I hit a breakpoint:

![gpr](https://user-images.githubusercontent.com/175644/27843221-b0d65ff4-6111-11e7-9dfb-95c0417ee9a1.JPG)

Can this be changed so that one can see the real data in a debugger?

Thanks :)

**Comment by dillonhuff** [comment]
Thanks for getting back to me.

I do not have MSVC (I use a mac), so I cannot see your problems firsthand.

I have made some changes to the code to try to fix the compilation errors you mentioned. The current version should now compile on MSVC 15 if it has C++ 11 support.

Re data in the debugger: When you say "Can this be changed so that one can see the real data in a debugger?" what do you mean by "the real data". What specifically are you expecting to see in the debugger that you do not see? I have not used the MSVC debugger so I do not know what it normally shows you.

My guess is that since the library is compiled with -O2 and is not compiled with debug symbols on there is some debug information that is missing.

I have added debug and release settings to the CMakeLists.txt of the project. My suggestion would be to set the CMAKE_CXX_FLAGS_DEBUG variable in CMakeLists.txt to whatever the msvc command is for debug symbols (the clang++ flag for adding debug symbols is -g, so I have added it to the CMAKE_CXX_FLAGS_DEBUG variable), then re-build the project with CMAKE_BUILD_TYPE=Release.

Unrelated but what are you trying to do with the G-code parser? I'm curious about what people want to use this G-code parser for.

**Comment by Kulitorum** [comment]
I will answer your last question first :)

I develop and build 3d printers from scratch, starting from a specification either from a customer or my own need. I do the CAD work, produce the mechanicals and build firmware for the machines and I use or sell the machines.

As a part of this, I often need to manipulate the gcode so I can test stuff that has not been done before. One example is recently I made a small program that analyzes gcode and adds a new axis to it, which would rotate the printhead of a printer to match the tangential direction of the direction being printed.

To do that, I needed to sometimes add new lines of code when the printer has to stop and rotate the head in place, and at other times just to add the rotation to an existing line of code.

Right now I am trying to add mixing to a two-in-one-out printhead, by retracting one filament while extruding another. So I will need to cut all moves in the gcode into smaller pieces and add oscillating movements to the two extruders, while maintaining the pressure in the printhead. The purpose is to blend two colors together inside the printhead while printing.

So while manipulating gcode this way, it would be a lot easier if I could read the numbers and commands directly in the debugger, which I cannot the way the code is written now, because everything (all the real data) ends in a void pointer, so the debugger does not know how to display the data deep down in the data structures.

For reference, I am not using your CMake, but rather just drop the cpp and h files in my own project and go from there.

BTW, I am a self-taught programmer and never took a single course, so I may not have the perfect understanding of proper structural programming that you clearly do, but am more of a hacker.

Would it be feasible to store the data directly inside the vectors rather than pointers to them? - What would be the downside?

**Comment by dillonhuff** [comment]
Thanks for getting back to me. Sounds like you are doing very cool stuff!

As far as examining the debugger goes, you wrote:

"Would it be feasible to store the data directly inside the vectors rather than pointers to them? - What would be the downside?"

In the original design it would not be possible to store the list of chunks directly in a vector. The reason that blocks store a list of pointers to chunks instead of just a list of chunk objects is because chunk is an abstract class with 2 subclasses: one for comments and one for word addresses. Each of those classes occupies a different amount of memory, so the compiler does not know how to create a vector<chunk> because each chunk might have a different size. This is a common source of difficulty in C++ code. If you are interested to learn more about this there are many explanations on the internet. Here is one:

https://stackoverflow.com/questions/37911552/why-i-can-not-use-abstract-class-in-stdvector

To avoid this problem I have re-written the internal part of the parser so that the chunk data structure is not abstract. In the new design there are no subclasses for comments and word address pairs, every chunk object includes fields for both comments and word-addresses, but when a chunk is a comment the word-address fields are set to default values and are not used, and when the chunk is a word-address pair the fields for comment data are set to default values and not used.

If you copy the new parser in this repo into your code you should now be able to see each chunks actual fields in the debugger.

I have tested this with LLDB (the native mac debugger) and I can see the fields of each chunk in each block during debugging.

Let me know if that worked. Also it would be great if you would give this repo a star to increase its visibility!

**Comment by Kulitorum** [comment]
Thank you too :)

Debugging is better now, but still not quite readable. Maybe we could just store the original string in each block as a std::string for readability, and only have it there in debug builds? It would ofcause need to be artificially created for blocks that are generated and inserted on the fly. - Would it be possible to just generate the string every time a block is changed?

This is what I am getting now:

![gpr2](https://user-images.githubusercontent.com/175644/27886984-bfe9c0e4-61de-11e7-9380-f290ebe49b4c.JPG)

Thanks for the effort :)

How do I give it a star?

You can see some of my projects here: https://www.youtube.com/user/KulitorumCom/videos

**Comment by dillonhuff** [comment]
Michael,

I have added your suggestion to the code. class block now has a field called ```debug_text``` which you should be able to view in the debugger.

To set the ```debug_text``` of a block to any string you want you can call the method:
```c++
void set_debug_text(const std::string& new_debug_text);
```

in class block. I assume that usually you will want to set the ```debug_text``` to be a string representation of the block itself, so for that you can call the method:

```c++
void set_debug_text();
```

For convenience I have also added a new parsing function:
```c++
gcode_program parse_gcode_saving_block_text(const std::string& program_text);
```
Which sets the ```debug_text``` of each block automatically.

I have also added an example of how to create a block on the fly and set its debug text in main.cpp

To star the repository log into your github account, navigate to this repository and look in the top right corner of the screen just below the black toolbar at the very top of the screen. There should be options to "Watch", "Star", or "Fork" the repository. Click the button with the star icon to star the repo. After you click it the star count should go from zero to one. You can see a screenshot from my computer that shows the watch, star, and fork buttons below the black toobar and above the green "New Issue" button.

<img width="1280" alt="screen shot 2017-07-05 at 4 38 56 pm" src="https://user-images.githubusercontent.com/3387568/27889325-775bb9a6-61a0-11e7-9f3e-88a02c594af3.png">
